### ISSUE TITLE
why is MAX_DATA_BYTES 4096?

### ISSUE THREAD

**Issue by JAndrassy** [gmag11/FirmataMaster#2]
reason for huge int[] buffer?

**Comment by jandrassy** [comment]
Martin, please answer

**Comment by gmag11** [comment]
Actually, I don't remember. I had some problems with softserial library and probably tried to increase buffer size for testing and, finally, this test was not removed.
Could you test a smaller value? Arduino Firmata has this value set to 64. You can try that.

**Comment by jandrassy** [comment]
#3
